### ISSUE TITLE
Recommend using underscore rather hyphens in function name ssh-find-agent

### ISSUE THREAD

**Issue by ayen-tibco** [wwalker/ssh-find-agent#12]
Since most linux systems symlin /usr/bin/sh->bash, I recommend using underscore in replacement of hyphens in the function name. Otherwise you will get the error 

`ssh-find-agent': not a valid identifier

**Comment by javabrett** [comment]
This request looks valid, but I'm curious which version of `bash` caused you problems here.  Allowing the hyphens is not guaranteed under POSIX, but many versions of bash seem to allow them.  Many shells are known not to.

@wwalker what could be reasonably done here - maybe change to `ssh_find_agent` and create an ok-if-fails registration of an alias for the original `ssh-find-agent` pointing to the new name, then things should work the same on `bash` and wherever currently working?

**Comment by wwalker** [comment]
https://github.com/wwalker/ssh-find-agent/commit/17d7d886090f9f45e685ffd9e83c827bcb8a7832

Should fix this.

**Comment by tydlwav** [comment]
@wwalker Just reminding you to close the issue since it's solved.

**Comment by wwalker** [comment]
:-) Thanks tydlwav
