### ISSUE TITLE
authorized_keys

### ISSUE THREAD

**Issue by Raizo62** [wwalker/ssh-find-agent#19]
Hi

Your script uses the file ".ssh/authorized_keys", but you don't verify before if this file exists (in my case, there was no)

**Comment by javabrett** [comment]
I realise it is easy-enough to test, but probably worth including the error output and consequence here.

**Comment by Raizo62** [comment]
It shows a bad output : "-bash: /home/login/.ssh/authorized_keys: Aucun fichier ou dossier de ce type". (<- No files or folders of this type)
Sorry, i don't know consequence. But an error message is never great ;-)
(On my system, I created an empty file.)

**Comment by dmaksimovic** [comment]
Same issue here. I have to manually edit the script to get rid of the error message. Why does it unconditionally even look at this file?? It's not necessary for what this script is used for afaik

**Comment by kingmilo** [comment]
The script attempts to interact with the authorized_keys file twice. One can either create a blank authorized_keys file or change the code to test for the existence of the file:

if [ -e ~/.ssh/authorized_keys ] ; then
                _FINGERPRINTS=$(fingerprints ~/.ssh/authorized_keys)
fi

if [ -e ~/.ssh/authorized_keys ] ; then
        authorized_entry=$(fingerprints ~/.ssh/authorized_keys | grep $fingerprint)
fi

**Comment by javabrett** [comment]
@wwalker I believe that this one is safe to close, thanks!
