### ISSUE TITLE
Failure running under zsh

### ISSUE THREAD

**Issue by jrs65** [wwalker/ssh-find-agent#25]
If I run on zsh with the current master I get a failure:
```
fingerprints:3: bad pattern: #
```
I think this can be fixed by escaping the hash in the pattern [here](https://github.com/wwalker/ssh-find-agent/blob/65fe3bad96397d23c263505ce89dfc295186bef6/ssh-find-agent.sh#L121). That is
```
-        [[ -n $l && ${l###} = $l ]] && ssh-keygen -l -f /dev/stdin <<<$l
+        [[ -n $l && ${l##\#} = $l ]] && ssh-keygen -l -f /dev/stdin <<<$l
```

I've checked that this change still produces the correct behaviour in the test on both bash and zsh, but I haven't done anything more extensive.

**Comment by dvn0** [comment]
>The solution resolves the issue; running `ssh-find-agent` afterwards results in no agents being found on zsh.
It will find agents in bash though

I am experiencing this too. I'm going to work on a patch. Hopefully @wwalker is still watching for pull requests :)

**Comment by dquist** [comment]
For zsh it is much easier to just use the `ssh-agent` plugin which does exactly what this script is trying to accomplish.

**Comment by mritzmann** [comment]
Haven't tried it, but maybe the following is enough?

```git
diff --git a/ssh-find-agent.sh b/ssh-find-agent.sh
index 7cb5fad..47bd3ef 100755
--- a/ssh-find-agent.sh
+++ b/ssh-find-agent.sh
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 # Copyright (C) 2011 by Wayne Walker <wwalker@solid-constructs.com>
 #
 # Released under one of the versions of the MIT License.
```

**Comment by wwalker** [comment]
The tests pass in bash, but zsh tests fail.  I'll have to create a test.zsh file
