### ISSUE TITLE
Travis repo link is missing

### ISSUE THREAD

**Issue by javabrett** [wwalker/ssh-find-agent#26]
Just a polite enquiry about the Travis integration - back in 2317f2edab98542d553a3f40d70afe4679e561b6 some tests and a Travis build were added - since then it looks like the Travis repo has gone: https://travis-ci.org/wwalker/ssh-find-agent = "We couldn't find the repository wwalker/ssh-find-agent".

**Comment by wwalker** [comment]
Fixed.
Passing :-)
Closing
