### ISSUE TITLE
 MacOS (at least 10.14) directories "wrong"

### ISSUE THREAD

**Issue by hevisko** [wwalker/ssh-find-agent#28]
Hi there,

 Under macOs 10.14.6, the following is places/examples of ssh-agent listening:

The "stock" macOS ssh-agent listening under launchd:

> /private/tmp/com.apple.launchd.{RandomString}/Listeners

The HomeBrew OpenSSH:

> /var/folders/4q/{Random-string}/T//ssh-{randomg-string}/agent.{PID}

This is compared to `/tmp` that points to `private/tmp` thus this script doesn't match any thing for macOs 10.14.6 ;(

**Comment by javabrett** [comment]
@hevisko can you outline the use-case for using this on MacOS?

I find that `ssh-agent` is already running, and that `launchd` has set `SSH_AUTH_SOCK` in any shell that I launch (to a path starting with `/private/tmp` as you point out).  10.15.2 here.

What needs do you have for `ssh-find-agent` on MacOS?

**Comment by hvisage** [comment]
When I use the HomeBrew with newer versions of OpenSSH, the paths isn't the "normal" `{/private}/tmp`

Don't have a 10.15.x to test with.

My "issue" is that I keep needing and using OpenSSH versions later than the versions shipped with MacOS, especially as I typically only got to the newer MacOS later than others for a stability/effort of upgrading reasons.

**Comment by javabrett** [comment]
In case it is helpful, there’s a detailed blog on switching the macOS `ssh-agent` over to the Homebrew dust version at https://coderwall.com/p/qdwcpg/using-the-latest-ssh-from-homebrew-on-osx . That should then retain keychain integration etc.

**Comment by wwalker** [comment]
Closing.
