### ISSUE TITLE
Doesn't work on AIX where the fingerprints function relies on /dev/stdin

### ISSUE THREAD

**Issue by sshtx** [wwalker/ssh-find-agent#29]
A representation of stdin as /dev/stdin doesn't exist in AIX.

**Comment by wwalker** [comment]
Which version of AIX?
Any idea where I can get a plain user account on an AIX machine?
I assume you are running bash on AIX?
If so, checkout the 29-aix branch and see if that works on AIX

**Comment by wwalker** [comment]
Merged the fix.  Don't have an account to test on AIX, closing.

**Comment by sshtx** [comment]
Just saw this now, will test tomorrow and let you know. ksh93 typically is the shell being utilized.
