### ISSUE TITLE
Beware libpam-tmpdir and TMP and TMPDIR environment variables

### ISSUE THREAD

**Issue by gdevenyi** [wwalker/ssh-find-agent#52]
libpam-tmpdir sets "more secure" per-user TMP/TMPDIRs

However, it turns out, ssh-agent does not properly honour TMPDIR
https://www.mail-archive.com/debian-ssh@lists.debian.org/msg05602.html

I ran into this today, ssh-agent was happily still dumping its sockets in `/tmp/` which TMPDIR was defined elsewhere, and ssh-find-agent could no longer find anything.

**Comment by wwalker** [comment]
Guess I'll need to address that.  

Probably default to looking in `/tmp` And in `$TMPDIR`, with an option to specify a path to search.

Maybe `--ssh-agent-path` and/or `$SSH_AGENT_PATH`

Yout thoughts on that @gdevenyi ?

**Comment by gdevenyi** [comment]
Yes, a default of both the basic system /tmp and the $TMPDIR sounds reasonable, with manual specification/ENV_VAR also an option.

Perhaps prefix the env var with SSH_FIND_AGENT_

**Comment by wwalker** [comment]
already have `_TMPDIR_OVERRIDE`

will still add `SSH_AGENT_PATH` though

**Comment by wwalker** [comment]
@gdevenyi Please pull branch `52` and see if it works for you.  I've done some testing and it seems good to me.  I didn't add the command line option that I originally intended to.  I'm thinking it is better to just set the environment variable; however, I am very open to feedback.

Branch `52` is the same as my PR #53 .

**Comment by wwalker** [comment]
I've used this for a couple of weeks, I don't have anything set up using TMP or TMPDIR directly but it does still find stuff in /tmp when I set TMPDIR or TMP elsewhere

Going to merge it into master, and tag as 1.0.1 (as it maintains backward compatibility with previous env vars used to control search locations)

**Comment by gdevenyi** [comment]
sorry for the delay, I had to reinstall libpam-tmpdir  to test this.

It seems to work as expected now, finding the agent again even with my tmpdir default being off somwhere else.

**Comment by wwalker** [comment]
Thank you @gdevenyi !
