### ISSUE TITLE
Typo in ssh-find-agent.sh

### ISSUE THREAD

**Issue by jmullan** [wwalker/ssh-find-agent#55]
https://github.com/wwalker/ssh-find-agent/blob/034cc1f15c3c2e3a969967f2a20e65e7416b7594/ssh-find-agent.sh#L218

this says `usage` instead of `sfa_usage` which causes some old invocations to fail somewhat silently

**Comment by wwalker** [comment]
@jmullan  Thank you!

**Comment by jmullan** [comment]
Thank you! I was probably going to get to a PR at some point but ... _gestures at everything_
